### ISSUE TITLE
wish: a bit more documentation

### ISSUE THREAD

**Issue by markstos** [tsub/fish-fzf-git-recent-branch#1]
If I try `fzf_git_recent_branch`, I can select a path, but then it exits with:

`fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths`.

I also see there is a key binding for "Control-B". I tried typing "Control-B" after `git checkout`, but I get a blank list to select from if I do that. 

I try just typing `Control B` on an empty command line, but that results in the same fatal error as above. 

Could you elaborate on the documentation a little more to elaborate on whatever it is I'm missing as a new user?

Thanks.

**Comment by markstos** [comment]
I'm using Fish 3.

**Comment by markstos** [comment]
Nevermind, I found out the Fish/Git integration is good enough already: https://twitter.com/MarkStosberg/status/1158866018539909125 Uninstalling this.

**Comment by tsub** [comment]
Thank you for using.
I could not reproduce it in my machine. Please let me know if you get up again.
